GENERAL_SEP_PAT = "--------------"  # Same length as Langchain's separator
CODE_BLOCK_PAT = "```\n{}\n```"
TRIPLE_BACKTICK = "```"
QUESTION_PAT = "Anfrage:"
FINAL_QUERY_PAT = "Finale Anfrage:"
THOUGHT_PAT = "Gedanke:"
ANSWER_PAT = "Antwort:"
ANSWERABLE_PAT = "Beantwortbar:"
FINAL_ANSWER_PAT = "Finale Antwort:"
QUOTE_PAT = "Zitat:"
QUOTES_PAT_PLURAL = "Zitate:"
INVALID_PAT = "Ungültig:"
SOURCES_KEY = "sources"

DEFAULT_IGNORE_STATEMENT = " Ignoriere alle Kontext-Dokumente, die nicht relevant sind."
